version: "3.8"
services:
  dev-postgres:
    image: postgres:14.4-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: karaoke-song
      POSTGRES_PASSWORD: karaoke-song
      POSTGRES_DB: karaoke-song
    restart: always
    networks:
      - lesson
networks:
  lesson: